### ISSUE TITLE
مشکل رم و سی پی یو در تانل pingtunnel

### ISSUE THREAD

**Issue by ali-frm** [Azumi67/ICMP_tunnels#1]
سلام توسعه دهنده عزیز
اسکریپت pingtunnel  وقتی یه ذره ترافیک روش میاد رم و سی پی یو سرور رو کامل درگیر میکنه. آیا راه حلی برای این موضوع وجود داره ؟

**Comment by Azumi67** [comment]
سلام. من کمی تغییرات در کامند ها دادم و مشکل بهتر شد. اما من مصرف شخصی را میتونم تایید کنم. لطفا دوباره تست کنید و به من اطلاع بدید. 
من بوسیله speedtest بررسی کردم.
در حال حاضر روی یک هسته cpu ، حدود 20 درصد را اشغال میکند در صورتی که قبلا 100 درصد بود.

**Comment by ali-frm** [comment]
درصد درگیری cpu با اسپید تست بهتر شده، پینگ اسپید دست حدود ۴۰ میلی ثانیه بالاتر رفته همچنین پهنای باند کمتر شده

**Comment by Azumi67** [comment]
میتونم کمی بهترش کنم اما 40 درصد cpu رو درگیر میکنه. الان تغییرات رو اعمال کردم.
